#Deployment - машина создающая, управляющая Pod'ами
#ClusterIP - сервис или адресс по которому можно достучаться из Ingress Controller в Pod platforms
aapiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformservice
  template:
    metadata:
      labels:
        app: platformservice
    spec:
      containers:
        - name: platformservice
          image: simonzhigailo/platformservice:latest
          ports:
            - containerPort: 80  # gRPC (HTTP/2)
            - containerPort: 81  # HTTP (обычные контроллеры)
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: CommandServiceUrl
              value: "http://commands-clusterip-srv"
          resources:
            limits:
              memory: "256Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: platforms-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformservice
  ports:
    - name: grpc
      protocol: TCP
      port: 80
      targetPort: 80  # gRPC (HTTP/2)
    - name: http
      protocol: TCP
      port: 81
      targetPort: 81  # обычный HTTP